'use client';
import {useEffect,useState} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {roles,interestSchema,type InterestInput} from '@/lib/interest';
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
export function InterestForm(){const[name,setName]=useState('');const[email,setEmail]=useState('');const[role,setRole]=useState('');const[organization,setOrganization]=useState('');const[message,setMessage]=useState('');const[consent,setConsent]=useState(false);const[website,setWebsite]=useState('');const[status,setStatus]=useState<'idle'|'saving'|'success'|'error'>('idle');const[error,setError]=useState('');
 async function save(input:unknown){const p=interestSchema.safeParse(input);if(!p.success){setError('Enter your name, a valid email, your role and consent to be contacted.');setStatus('error');throw new Error('Invalid registration details or missing consent.')}setStatus('saving');setError('');try{const res=await fetch('/api/interest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p.data)});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||'Registration is temporarily unavailable.');setStatus('success');return{status:'interest_recorded',access:'not_yet_available'}}catch(e){const msg=e instanceof Error?e.message:'Could not save your interest.';setError(msg);setStatus('error');throw e}}
 useEffect(()=>{const ctx=(document as Document&{modelContext?:ModelContext}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(ctx.registerTool({name:'register_labs_interest',description:'Record interest in CyberMindSpace Labs and show confirmation. Requires explicit consent to contact; does not grant lab access.',inputSchema:{type:'object',properties:{name:{type:'string'},email:{type:'string'},role:{type:'string',enum:[...roles]},organization:{type:'string'},message:{type:'string'},consent:{type:'boolean',const:true}},required:['name','email','role','consent'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{const parsed=interestSchema.parse(input);setName(parsed.name);setEmail(parsed.email);setRole(parsed.role);setOrganization(parsed.organization);setMessage(parsed.message);setConsent(parsed.consent);return save(parsed)}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 if(status==='success')return <div className="interest-success" role="status"><span className="eyebrow">INTEREST RECORDED</span><h2>You’re on the list.</h2><p>Thank you for your interest in CyberMindSpace Labs. We’ll use your details to contact you about relevant pilots, research collaboration or future access.</p><p>The platform is in development. Registration does not grant immediate access or create a paid subscription.</p><a className="button" href="/research/thesis">Explore the research thesis ↗</a></div>;
 return <form className="interest-form" onSubmit={e=>{e.preventDefault();void save({name,email,role,organization,message,consent,website}).catch(()=>{})}}><div className="form-row"><label htmlFor="interest-name">Name<input id="interest-name" autoComplete="name" required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label htmlFor="interest-email">Email<input id="interest-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label></div><label htmlFor="interest-role">I’m joining as<Select value={role} onValueChange={setRole} required><SelectTrigger id="interest-role" className="role-select"><SelectValue placeholder="Select your role"/></SelectTrigger><SelectContent position="popper">{roles.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label><label htmlFor="interest-org">Organization <span>optional</span><input id="interest-org" autoComplete="organization" maxLength={160} value={organization} onChange={e=>setOrganization(e.target.value)} placeholder="Company, university or community"/></label><label htmlFor="interest-message">What would you like to explore? <span>optional</span><textarea id="interest-message" maxLength={1500} value={message} onChange={e=>setMessage(e.target.value)} placeholder="A course pilot, an AI-security question, a research collaboration…" rows={4}/></label><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div><label className="check-label consent" htmlFor="interest-consent"><Checkbox id="interest-consent" checked={consent} onCheckedChange={v=>setConsent(v===true)} required/>I agree that CyberMindSpace may store these details and contact me about Labs access, pilots and collaboration.</label><p className="form-privacy">Your details are used for this interest registration. To request removal, email <a href="mailto:info@cybermindspace.com?subject=Remove%20Labs%20interest%20registration">info@cybermindspace.com</a>. Please do not include secrets or sensitive customer data.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button" disabled={status==='saving'} type="submit">{status==='saving'?'Saving your interest…':'Register interest ↗'}</button><p className="footnote">No payment. No immediate access. Updates when there is something meaningful to share.</p></form>}
