'use client';
import {useState,useEffect} from 'react';
import {AttackSurface,LabPreview,Classroom,ScenarioCode,EventGraph,Questions} from './experiments';
const stages=['DEFINE','GENERATE','DEPLOY','ISOLATE','ATTACK','OBSERVE','EVALUATE','REPRODUCE'];
const descriptions=['Declare identities, assets, boundaries and the security property.','Validate a bounded scenario and resolve a versioned environment plan.','Provision synthetic services; verify readiness and vulnerability witnesses.','Enforce tenant identities, resource limits and default-deny egress.','Introduce one controlled adversarial input.','Collect tool requests, policy decisions and independent resource receipts.','Evaluate the property. Missing evidence cannot silently become a pass.','Rebuild the initial state and retain the declared limits of replay.'];
export function Header(){const[open,setOpen]=useState(false);return <header className="header"><a className="brand" href="/" aria-label="CyberMindSpace Labs home"><img src="/brand/logo-mark.png" alt="" width={40} height={16}/><span>CyberMindSpace <b>LABS</b></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="main-nav">Menu {open?'−':'+'}</button><nav id="main-nav" aria-label="Main navigation" className={open?'open':''}>{['Labs','AI Security','Platform','Research','Educators','Enterprise','Pricing'].map(x=><a key={x} href={'/'+x.toLowerCase().replace(' ','-')}>{x}</a>)}</nav><a className="nav-cta" href="/early-access">Talk to us ↗</a></header>}
export function Topology(){return <figure className="thesis-image-wrap"><img src="/images/thesisimage.png" width={1536} height={1024} loading="lazy" alt="Conceptual cutaway of a layered computing environment and its observable data flows"/><div className="thesis-image-wash"/><figcaption className="thesis-image-caption">RESEARCH STUDY / SYSTEM BOUNDARIES</figcaption></figure>}
export function Pipeline(){const[s,setS]=useState(0);return <div className="pipeline"><div className="stage-nav" aria-label="Explore the research lifecycle">{stages.map((x,i)=><button key={x} className={s===i?'selected':''} aria-pressed={s===i} onClick={()=>setS(i)}><small>0{i+1}</small>{x}</button>)}</div><div className="pipeline-body"><div aria-live="polite"><span className="eyebrow">PROPOSED LIFECYCLE / 0{s+1}</span><h3>{stages[s].toLowerCase()}<span className="blue">.</span></h3><p>{descriptions[s]}</p><button className="text-button" onClick={()=>setS((s+1)%8)}>Next stage →</button><pre>{`stage: ${stages[s].toLowerCase()}\ncontract: no_unauthorized_export\nexecution: architecture_walkthrough\nproduction_engine: not_deployed`}</pre></div><Topology/></div></div>}
export function Footer(){return <footer><div className="footer-title">CyberMindSpace <span>LABS</span></div><div className="footer-row"><p>Security practice. Systems research.</p><a href="https://www.cybermindspace.com">CyberMindSpace ↗</a><a href="mailto:partnerships@cybermindspace.com">partnerships@cybermindspace.com</a><a href="tel:+918184889557">+91 8184889557</a></div><div className="footer-row footer-meta"><span>© 2026 CyberMindSpace</span><a href="/research/thesis">Research thesis / 0.2</a><span>Independent research & development</span></div></footer>}
export function HomePage(){const[paused,setPaused]=useState(true);useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setPaused(media.matches);const change=()=>setPaused(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);return <><Header/><main id="main">
<section className="editorial-hero" data-paused={paused}><div className="hero-light-field" aria-hidden="true"><img className="hero-research-image" src="/images/hero-light-field.webp" width={1536} height={1024} fetchPriority="high" alt=""/><img className="hero-light-echo" src="/images/hero-light-field.webp" width={1536} height={1024} alt=""/></div><div className="hero-shade"/><div className="editorial-hero-content"><span className="eyebrow">CYBERMINDSPACE / SECURITY RESEARCH & LABS</span><h1>Understand<br/>the boundary.<br/><em>Prove what<br/>crossed it.</em></h1><p>Hands-on cybersecurity today.<br/>A research program for verifiable security experiments.</p><div className="actions"><a className="button" href="/research/thesis">Read the thesis ↗</a><a className="text-button" href="/labs">Explore the labs ↗</a></div></div><div className="editorial-hero-foot"><span>01 / INTENT → EXECUTION → EVIDENCE</span><span>RESEARCH PROGRAM · IN DEVELOPMENT</span><button className="hero-motion-control" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Play background':'Pause background'}</button></div></section>
<section className="section editorial-intro"><span className="eyebrow">THE QUESTION WE ARE BUILDING AROUND</span><div><h2>When an AI system acts,<br/>what actually happened?</h2><p className="lead">A reassuring answer can hide an unauthorized action. A missing trace can look like a clean run. Our research connects the security rule, the environment and the evidence needed to judge the outcome.</p><a className="text-button" href="/research/thesis#hypothesis">Read the precise hypothesis ↗</a></div></section>
<section className="editorial-split section"><figure className="research-photo"><img src="/images/boundary-study.webp" alt="Blue light refracting through a sequence of dark optical surfaces" width={1536} height={1024} loading="lazy"/><figcaption>STUDY 01 / TRUST BOUNDARIES · CONCEPTUAL ARTWORK</figcaption></figure><div><span className="eyebrow">RESEARCH / EVIDENCE CONTRACTS</span><h2>Every verdict<br/>has an obligation.</h2><p>Specify who may act on which resource. Capture the effect independently. Return a defensible result—or state exactly why the evidence is insufficient.</p><div className="research-principles">{[['01','Define','A bounded scenario, explicit identities and a testable property.'],['02','Observe','Resource receipts alongside requests and policy decisions.'],['03','Evaluate','Satisfied, violated or inconclusive. Execution health stays separate.']].map(([n,t,p])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}</div><a className="text-button" href="/platform">Explore the proposed architecture ↗</a></div></section>
<section className="section" id="ai"><div className="section-heading"><span className="eyebrow">INTERACTIVE / BOUNDED FIXTURE</span><h2>Change the control.<br/>Inspect the consequence.</h2><p>Run a synthetic export scenario. Compare enforcement, resource effects and incomplete evidence.</p></div><AttackSurface/></section>
<section className="section light-section"><div className="editorial-intro"><span className="eyebrow">LABS / PRACTICE THE FUNDAMENTALS</span><div><h2>Good security starts<br/>with hands-on work.</h2><p className="lead">Practice web security, access control, Linux and detection with established training environments. Explore our browser exercise here, or follow the catalog to independent lab providers.</p><a className="button" href="/labs">Open the lab catalog ↗</a></div></div><div className="practice-preview"><LabPreview/></div></section>
<section className="section editorial-split"><div><span className="eyebrow">RESEARCH THESIS / VERSION 0.2</span><h2>Built to be tested.<br/><em>Designed to be disputed.</em></h2><p>The thesis defines a narrow product kernel: security contracts for tool-using agents, independent evidence collection and reproducible evaluation. It includes failure modes, baseline comparisons and release gates.</p><p>These are engineering specifications and research hypotheses. Production validation remains work to be done.</p><a className="button" href="/research/thesis">Read the technical thesis ↗</a></div><figure className="research-photo"><img src="/images/silicon-study.webp" alt="Close study of silicon circuit topography illuminated in cobalt blue" width={1536} height={1024} loading="lazy"/><figcaption>STUDY 02 / COMPUTATIONAL SUBSTRATE · CONCEPTUAL ARTWORK</figcaption></figure></section>
<section className="section"><span className="eyebrow">EXPERIMENT WORKBENCH / SYNTHETIC DATA</span><h2>Inspect the contract<br/>and its evidence.</h2><ScenarioCode/><div className="workbench-gap"><EventGraph/></div><p className="footnote">These browser simulations execute bounded local rules. They do not run a live AI model or provision infrastructure.</p></section>
<section className="section"><span className="eyebrow">RESEARCH QUESTIONS</span><h2>Progress requires<br/>a falsifiable question.</h2><Questions/></section>
<section className="section"><Classroom/></section>
<section className="section final-cta"><span className="eyebrow">RESEARCH & INFRASTRUCTURE PARTNERSHIPS</span><h2>Bring a difficult<br/><em>security question.</em></h2><div><p>For research teams, educators and engineers<br/>working at the boundary of AI and security.</p><div className="contact-links"><a href="mailto:partnerships@cybermindspace.com">partnerships@cybermindspace.com ↗</a><a href="tel:+918184889557">+91 8184889557</a><a className="text-button" href="/early-access">Register collaboration interest ↗</a></div></div></section>
</main><Footer/></>}
